from config.config import CHROMATIC_SCALE, FRETBOARD_LEN, NUM_FRETS, FRETS, DEFAULT_KEY, DEFAULT_TUNING, DEFAULT_SCALE_INTERVALS, DEFAULT_SCALE_NOTES, DEFAULT_CHORD_INTERVALS, DEFAULT_CHORD_NOTES

__all__ = [

    "CHROMATIC_SCALE",
    "FRETBOARD_LEN",
    "NUM_FRETS",
    "FRETS",
    "DEFAULT_KEY",
    "DEFAULT_TUNING",
    "DEFAULT_SCALE_INTERVALS",
    "DEFAULT_SCALE_NOTES",
    "DEFAULT_CHORD_INTERVALS",
    "DEFAULT_CHORD_NOTES"
    
]
